# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            dockeraml/rotten-potatoes:latest
            dockeraml/rotten-potatoes:${{ github.run_number }}


          # List of a customs host-to-IP mapping (e.g., docker:10.180.0.1)
          add-hosts: # optional
          # List of extra privileged entitlement (e.g., network.host,security.insecure)
          allow: # optional
          # List of build-time variables
          build-args: # optional
          # List of additional build contexts (e.g., name=path)
          build-contexts: # optional
          # Builder instance
          builder: # optional
          # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
          cache-from: # optional
          # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
          cache-to: # optional
          # Optional parent cgroup for the container used in the build
          cgroup-parent: # optional
          # Build's context is the set of files located in the specified PATH or URL
          # List of metadata for an image
          labels: # optional
          # Load is a shorthand for --output=type=docker
          load: # optional, default is false
          # Set the networking mode for the RUN instructions during build
          network: # optional
          # Do not use cache when building the image
          no-cache: # optional, default is false
          # List of output destinations (format: type=local,dest=path)
          outputs: # optional
          # List of target platforms for build
          platforms: # optional
          # Always attempt to pull all referenced images
          pull: # optional, default is false
          
          # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
          secrets: # optional
          # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
          secret-files: # optional
          # Size of /dev/shm (e.g., 2g)
          shm-size: # optional
          # List of SSH agent socket or keys to expose to the build
          ssh: # optional
          # Sets the target stage to build
          target: # optional
          # Ulimit options (e.g., nofile=1024:1024)
          ulimit: # optional
          # GitHub Token used to authenticate against a repository for Git context
          github-token: # optional, default is ${{ github.token }}
