# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            dockeraml/rotten-potatoes:latest
            dockeraml/rotten-potatoes:${{ github.run_number }}
